baseURL = 'https://monumental-alpaca-2b521e.netlify.app'
title = 'Raising Hops'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'
canonifyURLs = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
disablekinds = [ "taxonomy", "term"]
paginate = 8