baseURL = 'https://raisinghops.fr'
title = 'Raising Hops'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'
canonifyURLs = true
enableRobotsTXT = true
disablekinds = [ "taxonomy", "term"]
paginate = 8